name: On Pull Request (CI)

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre-commit-check:
    name: ğŸª Pre-commit hooks workflow
    uses: ./.github/workflows/workflow_pre_commit_check.yml
    secrets: inherit

  python-tests-check:
    name: ğŸÃ—ğŸ§ª python tests
    uses: ./.github/workflows/workflow_python_tests.yml
    secrets: inherit
